apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-nlu
  labels:
    app: search-nlu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-nlu
  template:
    metadata:
      labels:
        app: search-nlu
    spec:
      containers:
      - name: search-nlu
        image: de.icr.io/cloud-lab-fa/search-nlu:1.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: NLU_BASEURL
          valueFrom:
            configMapKeyRef:
              name: search-nlu-configmap
              key: NLU_BASEURL
        - name: NLU_VERSION
          valueFrom:
            configMapKeyRef:
              name: search-nlu-configmap
              key: NLU_VERSION
        - name: NLU_APIKEY
          valueFrom:
            secretKeyRef:
              name: search-nlu-secret
              key: NLU_APIKEY
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
            
