apiVersion: v1
kind: Service
metadata:
  name: search-nlu
  labels:
    app: search-nlu
spec:
  type: ClusterIP
  selector:
    app: search-nlu
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000